class GainersData:
    def __init__(self, data):
        self.tickerId = [int(i['ticker']['tickerId']) if isinstance(i['ticker']['tickerId'], str) else i['ticker']['tickerId'] for i in data if 'ticker' in i and 'tickerId' in i['ticker']]
        
        self.exchangeId = [i['exchangeId'] for i in data if 'exchangeId' in i]
        self.type = [i['type'] for i in data if 'type' in i]
        self.secType = [i['secType'] for i in data if 'secType' in i]
        self.regionId = [i['regionId'] for i in data if 'regionId' in i]
        self.currencyId = [i['currencyId'] for i in data if 'currencyId' in i]
        self.currencyCode = [i['currencyCode'] for i in data if 'currencyCode' in i]
        self.name = [i['name'] for i in data if 'name' in i]
        self.symbol = [i['symbol'] for i in data if 'symbol' in i]
        self.disSymbol = [i['disSymbol'] for i in data if 'disSymbol' in i]
        self.disExchangeCode = [i['disExchangeCode'] for i in data if 'disExchangeCode' in i]
        self.exchangeCode = [i['exchangeCode'] for i in data if 'exchangeCode' in i]
        self.listStatus = [i['listStatus'] for i in data if 'listStatus' in i]
        self.template = [i['template'] for i in data if 'template' in i]
        self.derivativeSupport = [i['derivativeSupport'] for i in data if 'derivativeSupport' in i]
        self.isPTP = [i['isPTP'] for i in data if 'isPTP' in i]
        self.tradeTime = [i['tradeTime'] for i in data if 'tradeTime' in i]
        self.faTradeTime = [i['faTradeTime'] for i in data if 'faTradeTime' in i]
        self.status = [i['status'] for i in data if 'status' in i]
        self.close = [i['close'] for i in data if 'close' in i]
        self.change = [i['change'] for i in data if 'change' in i]
        self.changeRatio = [i['changeRatio'] for i in data if 'changeRatio' in i]
        self.marketValue = [i['marketValue'] for i in data if 'marketValue' in i]
        self.volume = [i['volume'] for i in data if 'volume' in i]
        self.turnoverRate = [i['turnoverRate'] for i in data if 'turnoverRate' in i]
        self.regionName = [i['regionName'] for i in data if 'regionName' in i]
        self.regionIsoCode = [i['regionIsoCode'] for i in data if 'regionIsoCode' in i]
        self.peTtm = [i['peTtm'] for i in data if 'peTtm' in i]
        self.preClose = [i['preClose'] for i in data if 'preClose' in i]
        self.fiftyTwoWkHigh = [i['fiftyTwoWkHigh'] for i in data if 'fiftyTwoWkHigh' in i]
        self.fiftyTwoWkLow = [i['fiftyTwoWkLow'] for i in data if 'fiftyTwoWkHigh' in i]
        self.open = [i['open'] for i in data if 'open' in i]
        self.high = [i['high'] for i in data if 'high' in i]
        self.low = [i['low'] for i in data if 'low' in i]

