"""REPLACE WITH DISCORD CHANNEL WEBHOOKS TO MONITOR SPECIFIC COUNTRY TICKERS / INDEX TICKERS"""

##CHINA##

ACH="YOUR WEBHOOK CHANNEL URL HERE"
AMBO="YOUR WEBHOOK CHANNEL URL HERE"
APTO="YOUR WEBHOOK CHANNEL URL HERE"
BABA="YOUR WEBHOOK CHANNEL URL HERE"
BEKE="YOUR WEBHOOK CHANNEL URL HERE"
BIDU="YOUR WEBHOOK CHANNEL URL HERE"
DADA="YOUR WEBHOOK CHANNEL URL HERE"
DAO="YOUR WEBHOOK CHANNEL URL HERE"
CD="YOUR WEBHOOK CHANNEL URL HERE"
DQ="YOUR WEBHOOK CHANNEL URL HERE"
EDU="YOUR WEBHOOK CHANNEL URL HERE"
EH="YOUR WEBHOOK CHANNEL URL HERE"
EJH="YOUR WEBHOOK CHANNEL URL HERE"
FENG="YOUR WEBHOOK CHANNEL URL HERE"
GDS="YOUR WEBHOOK CHANNEL URL HERE"
GHG="YOUR WEBHOOK CHANNEL URL HERE"
GSH="YOUR WEBHOOK CHANNEL URL HERE"
GOTU="YOUR WEBHOOK CHANNEL URL HERE"
GTYH="YOUR WEBHOOK CHANNEL URL HERE"
HNP="YOUR WEBHOOK CHANNEL URL HERE"
HTHT="YOUR WEBHOOK CHANNEL URL HERE"
HUYA="YOUR WEBHOOK CHANNEL URL HERE"
JD="YOUR WEBHOOK CHANNEL URL HERE"
JG="YOUR WEBHOOK CHANNEL URL HERE"
JMIA="YOUR WEBHOOK CHANNEL URL HERE"
JRJC="YOUR WEBHOOK CHANNEL URL HERE"
KONG="YOUR WEBHOOK CHANNEL URL HERE"
KC="YOUR WEBHOOK CHANNEL URL HERE"
AMGN="YOUR WEBHOOK CHANNEL URL HERE"
LFC="YOUR WEBHOOK CHANNEL URL HERE"
LFT="YOUR WEBHOOK CHANNEL URL HERE"
LGVW="YOUR WEBHOOK CHANNEL URL HERE"
LIZI="YOUR WEBHOOK CHANNEL URL HERE"
LK="YOUR WEBHOOK CHANNEL URL HERE"
MOTV="YOUR WEBHOOK CHANNEL URL HERE"
NIO="YOUR WEBHOOK CHANNEL URL HERE"
NPTN="YOUR WEBHOOK CHANNEL URL HERE"
PDD="YOUR WEBHOOK CHANNEL URL HERE"
QD="YOUR WEBHOOK CHANNEL URL HERE"
QIWI="YOUR WEBHOOK CHANNEL URL HERE"
SFUN="YOUR WEBHOOK CHANNEL URL HERE"
SMICY="YOUR WEBHOOK CHANNEL URL HERE"
TAL="YOUR WEBHOOK CHANNEL URL HERE"
TC="YOUR WEBHOOK CHANNEL URL HERE"
TME="YOUR WEBHOOK CHANNEL URL HERE"
TUYA="YOUR WEBHOOK CHANNEL URL HERE"
TSM="YOUR WEBHOOK CHANNEL URL HERE"
UPWK="YOUR WEBHOOK CHANNEL URL HERE"
VIPS="YOUR WEBHOOK CHANNEL URL HERE"
ZLAB="YOUR WEBHOOK CHANNEL URL HERE"

china_hooks = { 
    'ACH':ACH,
    'AMBO':AMBO,
    'APTO':APTO,
    'BABA':BABA,
    'BEKE':BEKE,
    'BIDU':BIDU,
    'DADA':DADA,
    'DAO':DAO,
    'CD':CD,
    'DQ':DQ,
    'EDU':EDU,
    'EH':EH,
    'EJH':EJH,
    'FENG':FENG,
    'GDS':GDS,
    'GHG':GHG,
    'GSH':GSH,
    'GOTU':GOTU,
    'GTYH':GTYH,
    'HNP':HNP,
    'HTHT':HTHT,
    'HUYA':HUYA,
    'JD': JD,
    'JG': JG,
    'JMIA':JMIA,
    'JRJC':JRJC,
    'KONG':KONG,
    'KC': KC,
    'LFC':LFC,
    'LFG':LFT,
    'LGVW':LGVW,
    'LIZI':LIZI,
    'LK':LK,
    'MOTV':MOTV,
    'NIO':NIO,
    'NPTN':NPTN,
    'PDD':PDD,
    'QD':QD,
    'QIWI':QIWI,
    'SFUN':SFUN,
    'SMICY':SMICY,
    'TAL':TAL,
    'TC':TC,
    'TME':TME,
    'TUYA':TUYA,
    'TSM':TSM,
    'UPWK': UPWK,
    'VIPS': VIPS,
    'ZLAB': ZLAB,



##INDEX##

}   

AMC="YOUR WEBHOOK CHANNEL URL HERE"
GME="YOUR WEBHOOK CHANNEL URL HERE"
MULN="YOUR WEBHOOK CHANNEL URL HERE"
BBBY="YOUR WEBHOOK CHANNEL URL HERE"
meme_hooks = { 
    'AMC':AMC,
    'GME':GME,
    'MULN':MULN,
    'BBBY':BBBY,
}

AAPL="YOUR WEBHOOK CHANNEL URL HERE"
ADI="YOUR WEBHOOK CHANNEL URL HERE"
ADP="YOUR WEBHOOK CHANNEL URL HERE"
AMAT="YOUR WEBHOOK CHANNEL URL HERE"
AMZN="YOUR WEBHOOK CHANNEL URL HERE"
CSCO="YOUR WEBHOOK CHANNEL URL HERE"
CMCSA="YOUR WEBHOOK CHANNEL URL HERE"
COST="YOUR WEBHOOK CHANNEL URL HERE"
CTSH="YOUR WEBHOOK CHANNEL URL HERE"
AVGO="YOUR WEBHOOK CHANNEL URL HERE"
GILD="YOUR WEBHOOK CHANNEL URL HERE"
INTC="YOUR WEBHOOK CHANNEL URL HERE"
GOOG="YOUR WEBHOOK CHANNEL URL HERE"
FAST="YOUR WEBHOOK CHANNEL URL HERE"
FISV="YOUR WEBHOOK CHANNEL URL HERE"
INTU="YOUR WEBHOOK CHANNEL URL HERE"
MSFT="YOUR WEBHOOK CHANNEL URL HERE"
ILMN="YOUR WEBHOOK CHANNEL URL HERE"
NFLX="YOUR WEBHOOK CHANNEL URL HERE"
NVDA="YOUR WEBHOOK CHANNEL URL HERE"
PYPL="YOUR WEBHOOK CHANNEL URL HERE"
SBUX="YOUR WEBHOOK CHANNEL URL HERE"
TSLA="YOUR WEBHOOK CHANNEL URL HERE"
QCOM="YOUR WEBHOOK CHANNEL URL HERE"
PEP="YOUR WEBHOOK CHANNEL URL HERE"
MELI="YOUR WEBHOOK CHANNEL URL HERE"
MU="YOUR WEBHOOK CHANNEL URL HERE"
PAYX="YOUR WEBHOOK CHANNEL URL HERE"
TXN="YOUR WEBHOOK CHANNEL URL HERE"
KLAC="YOUR WEBHOOK CHANNEL URL HERE"
KHC="YOUR WEBHOOK CHANNEL URL HERE"
LRCX="YOUR WEBHOOK CHANNEL URL HERE"
MAR="YOUR WEBHOOK CHANNEL URL HERE"
MNST="YOUR WEBHOOK CHANNEL URL HERE"
VRSK="YOUR WEBHOOK CHANNEL URL HERE"
VRSN="YOUR WEBHOOK CHANNEL URL HERE"
VRTX="YOUR WEBHOOK CHANNEL URL HERE"
WBA="YOUR WEBHOOK CHANNEL URL HERE"
WDAY="YOUR WEBHOOK CHANNEL URL HERE"
XEL="YOUR WEBHOOK CHANNEL URL HERE"
ZM = "YOUR WEBHOOK CHANNEL URL HERE"
META="YOUR WEBHOOK CHANNEL URL HERE"
ISRG="YOUR WEBHOOK CHANNEL URL HERE"

index_hooks = { 
    'AAPL':AAPL,
    'ADI':ADI,
    'ADP':ADP,
    'AMGN': AMGN,
    'AMAT': AMAT,
    'AMZN': AMZN,
    'AVGO': AVGO,
    'META': META,
    'CSCO': CSCO,
    'CMCSA':CMCSA,
    'COST':COST,
    'CTSH': CTSH,
    'GILD': GILD,
    'INTC': INTC,
    'ISRG': ISRG,
    'GOOG': GOOG,
    'FAST': FAST,
    'FISV':FISV,
    'INTU':INTU,
    'MSFT':MSFT,
    'ILMN':ILMN,
    'NFLX':NFLX,
    'NVDA':NVDA,
    'PYPL':PYPL,
    'MU':MU,
    'TSLA':TSLA,
    'QCOM':QCOM,
    'SBUX':SBUX,
    'PEP':PEP,
    'MELI':MELI,
    'PAYX':PAYX,
    'TXN':TXN,
    'KLAC':KLAC,
    'KHC': KHC,
    'LRCX': LRCX,
    'MAR': MAR,
    'MNST': MNST,
    'VRSK': VRSK,
    'VRSN': VRSN,
    'VRTX': VRTX,
    'WBA': WBA,
    'WDAY': WDAY,
    'XEL': XEL,
    'ZM': ZM,



}

##INDIA##

AXIS="YOUR WEBHOOK CHANNEL URL HERE"
HDB="YOUR WEBHOOK CHANNEL URL HERE"
IBN="YOUR WEBHOOK CHANNEL URL HERE"
INFY="YOUR WEBHOOK CHANNEL URL HERE"
MAKE="YOUR WEBHOOK CHANNEL URL HERE"
REDY="YOUR WEBHOOK CHANNEL URL HERE"
SIFY="YOUR WEBHOOK CHANNEL URL HERE"
WIPRO="YOUR WEBHOOK CHANNEL URL HERE"
WNS="YOUR WEBHOOK CHANNEL URL HERE"
YTRA="YOUR WEBHOOK CHANNEL URL HERE"
YPRL="YOUR WEBHOOK CHANNEL URL HERE"
ZEEL="YOUR WEBHOOK CHANNEL URL HERE"


india_hooks = { 
    'AXIS': AXIS,
    'HDB': HDB,
    'IBN': IBN,
    'INFY': INFY,
    'MAKE': MAKE,
    'REDY': REDY,
    'SIFY': SIFY,
    'WIPRO': WIPRO,
    'WNS': WNS,
    'YTRA': YTRA,
    'YPRL': YPRL,
    'ZEEL': ZEEL

}


##RUSSIA##


GZFPY="YOUR WEBHOOK CHANNEL URL HERE"
LUKOY="YOUR WEBHOOK CHANNEL URL HERE"
MTL="YOUR WEBHOOK CHANNEL URL HERE"
MBT="YOUR WEBHOOK CHANNEL URL HERE"
NOVKY="YOUR WEBHOOK CHANNEL URL HERE"
NILSY="YOUR WEBHOOK CHANNEL URL HERE"
RNFTF="YOUR WEBHOOK CHANNEL URL HERE"
russia_hooks = { 
    'GZFPY': GZFPY,
    'LUKOY': LUKOY,
    'MTL': MTL,
    'MBT': MBT,
    'NOVKY': NOVKY,
    'NILSY': NILSY,
    'RNFTF': RNFTF



}
SPXW="YOUR WEBHOOK CHANNEL URL HERE"
SPY="YOUR WEBHOOK CHANNEL URL HERE"
TQQQ="YOUR WEBHOOK CHANNEL URL HERE"
SQQQ="YOUR WEBHOOK CHANNEL URL HERE"
QQQ="YOUR WEBHOOK CHANNEL URL HERE"
KRE="YOUR WEBHOOK CHANNEL URL HERE"
FXI="YOUR WEBHOOK CHANNEL URL HERE"
EEM="YOUR WEBHOOK CHANNEL URL HERE"
EWZ="YOUR WEBHOOK CHANNEL URL HERE"
IWM="YOUR WEBHOOK CHANNEL URL HERE"
ETF_BROAD_MARKET_HOOKS = { 
    'SPXW': SPXW,
    'SPY': SPY,
    'EEM': EEM,
    'FXI': FXI,
    'KRE': KRE,
    'QQQ': QQQ,
    'IWM': IWM,
    'SQQQ': SQQQ,
    'TQQQ': TQQQ,
    'EWZ': EWZ
}


stock_condition_hooks = {
    "Intermarket Sweep": "YOUR WEBHOOK URL HERE",
    "SSR In Effect": "YOUR WEBHOOK URL HERE",
    "Odd Lot Trade": "YOUR WEBHOOK URL HERE",
    "Closing Prints": "YOUR WEBHOOK URL HERE",
    "Derivatively Priced": "YOUR WEBHOOK URL HERE",
    "Opening Prings": "YOUR WEBHOOK URL HERE",
}

stock_exchange_hooks = { 
    "Nyse Arca, Inc": "YOUR WEBHOOK URL HERE",
    "New York Stock Exchange": "YOUR WEBHOOK URL HERE",
    "Finra Alternative Display Facility": "YOUR WEBHOOK URL HERE",
    "Nasdaq": "YOUR WEBHOOK URL HERE",
    "CboeEDGA": "YOUR WEBHOOK URL HERE",
    "Cboe EDGX": "YOUR WEBHOOK URL HERE",
    "Cboe BZX": "YOUR WEBHOOK URL HERE",
    "NYSE American, LLC": "YOUR WEBHOOK URL HERE",
    "Cboe BYX": "YOUR WEBHOOK URL HERE",
    "Investors Exchange": "YOUR WEBHOOK URL HERE",
    "Members Exchange": "YOUR WEBHOOK URL HERE",
    "MIAX Pearl": "YOUR WEBHOOK URL HERE",
    "Nasdaq Philadelphia Exchange LLC": "YOUR WEBHOOK URL HERE",
    "Consolidated Tape Association": "YOUR WEBHOOK URL HERE",
}



options_exchange_hooks = { 
    'NYSE American Options': "YOUR WEBHOOK URL HERE",
    'Boston Options Exchange': "YOUR WEBHOOK URL HERE",
    'Chicago Board Options Exchange': "YOUR WEBHOOK URL HERE",
    'MIAX Emerald, LLC': "YOUR WEBHOOK URL HERE",
    'Cboe EDGX Options': "YOUR WEBHOOK URL HERE",
    'Nasdaq Global Markets Exchange Group': "YOUR WEBHOOK URL HERE",
    'International Securities Exchange, LLC': "YOUR WEBHOOK URL HERE",
    'Nasdaq MRX Options Exchange': "YOUR WEBHOOK URL HERE",
    'MIAX International Securities Exchange, LLC': "YOUR WEBHOOK URL HERE",
    'NYSE Arca, Inc. - Options': "YOUR WEBHOOK URL HERE",
    'Options Price Reporting Authority': "YOUR WEBHOOK URL HERE",
    'MIAX Pearl, LLC - Options': "YOUR WEBHOOK URL HERE",
    'Nasdaq BX - Options': "YOUR WEBHOOK URL HERE",
    'Nasdaq Philadelphia Exchange, LLC - Options': "YOUR WEBHOOK URL HERE",
    'Cboe BZX Options Exchange': "YOUR WEBHOOK URL HERE",
    'MIAX Pearl, LLC': "YOUR WEBHOOK URL HERE",
    'Cboe EDGX': "YOUR WEBHOOK URL HERE",
    'Cboe C2 Options Exchange': "YOUR WEBHOOK URL HERE"
}

option_condition_hooks = { 
    "Intermarket Sweep Order": "YOUR WEBHOOK URL HERE",
    "Reopening Trade": "YOUR WEBHOOK URL HERE",
    "Canceled": "YOUR WEBHOOK URL HERE",
    "Single Leg Auction ISO": "YOUR WEBHOOK URL HERE",
    "Single Leg Auction Non ISO": "YOUR WEBHOOK URL HERE",
    "Single Leg Cross ISO": "YOUR WEBHOOK URL HERE",
    "Single Leg Cross Non ISO": "YOUR WEBHOOK URL HERE",
    "Single Leg Floor Trade": "YOUR WEBHOOK URL HERE",
    "Multi Leg auto-electronic trade": "YOUR WEBHOOK URL HERE",
    "Multi leg cross": "YOUR WEBHOOK URL HERE",
    "Multi Leg floor trade": "YOUR WEBHOOK URL HERE",
    "Multi Leg Auction against single leg(s)": "YOUR WEBHOOK URL HERE",
    "Stock Options Auction": "YOUR WEBHOOK URL HERE",
    "Stock Options Cross": "YOUR WEBHOOK URL HERE",
    "Stock Options floor trade": "YOUR WEBHOOK URL HERE",
    "Stock Options Auction against single leg(s)": "YOUR WEBHOOK URL HERE",
    "Stock Options floor trade against single leg(s)": "YOUR WEBHOOK URL HERE",
    "Multi Leg Floor Trade of Proprietary Products": "YOUR WEBHOOK URL HERE",
    "Multilateral Compression Trade of Proprietary Products": "YOUR WEBHOOK URL HERE",
    "Extended Hours Trade": "YOUR WEBHOOK URL HERE"
}

#Replace each instance of "YOUR WEBHOOK URL HERE" with the actual webhook URL you want to use for each corresponding options exchange or condition.






